//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] FatherOrSpouseName { get; set; }
        public byte[] MotherName { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string MaritalStatus { get; set; }
        public string CitizenShip { get; set; }
        public string ResidentialStatus { get; set; }
        public string Occupation { get; set; }
    }
}
